[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

